#!/bin/bash

SVC="cstbox-webservices"

# restarts the Web services server for the new package to be taken in account
# if the CSTBox is currently running
if [ -e /var/run/cstbox/cstbox-dbus.pid ] ; then
    echo "Restarting Web services API server"
    service $SVC restart
fi

